### ISSUE TITLE
Error in apply_treatment_effect(x = x, model_formula = model$model_formula, : object 'modifier' not found

### ISSUE THREAD

**Issue by dbent33** [RANDCorporation/optic#27]
Hi, 

I recently attended a workshop where Beth Ann shared this code. But I'm receiving an error. Can you give me an idea why this could be occurring if it's not a bug?

`
library(optic)
library(did)
library(augsynth)
library(fixest)
library(tidyr)
data(overdoses)
overdoses$crude.rate <- 1e5*(overdoses$deaths/overdoses$population)

ar <- optic_model(
  name = "AR",
type = "autoreg",
call = "lm",
formula = crude.rate ~ unemploymentrate + as.factor(year) + treatment_change,
se_adjust = "none")

ascm <- list(
name="ASCM",
type="multisynth",
model_call="multisynth",
model_formula=crude.rate ~ treatment_level | unemploymentrate,
model_args=list(unit=as.name("state"), time=as.name("year"), fixedeff=TRUE,
form=crude.rate ~ treatment_level | unemploymentrate),
se_adjust="none")

csa <- list(
  name="CSA",
type="did",
model_call="att_gt",
model_formula= ~ unemploymentrate,
model_args=list(yname="crude.rate", tname="year", idname="state",
gname="treatment_year", xformla = formula("~ unemploymentrate")),
se_adjust=c("none"))

five_percent_effect <- 0.05*mean(overdoses$crude.rate, na.rm = T)
ten_percent_effect <- 0.10*mean(overdoses$crude.rate, na.rm = T)
scenarios_no_confounding <- list(five_percent_effect, ten_percent_effect)

sim_config <- optic_simulation(
  x = overdoses,
  models = list(ar,ascm,csa),
  iters = 50,
  method = "no_confounding",
  unit_var = "state",
  treat_var = "state",
  time_var = "year",
  effect_magnitude = scenarios_no_confounding,
  n_units = c(5,30),
  effect_direction = c("neg"),
  policy_speed = c("instant","slow"),n_implementation_periods = c(6))

sim_results <- dispatch_simulations(
  sim_config,
  use_future = F,
  seed = 978,
  verbose = TRUE)
`

Error message:
Error in dispatch_simulations(sim_config, use_future = F, seed = 978,  : 
  attempted 10 percent of total iterations in single thread; something is not right, here's the most recent error: Error in apply_treatment_effect(x = x, model_formula = model$model_formula, : object 'modifier' not found

**Comment by pedroliman** [comment]
@maxgriswold, can you try to reproduce the issue with the version at main and the version you've been working on?

**Comment by pedroliman** [comment]
Hi @dbent33, the issue you were facing was solved by @maxgriswold. Can you install the package from github and try again?

You can install with:

```{r}
install.packages("remotes")
remotes::install_github("RANDCorporation/optic")
```

**Comment by dbent33** [comment]
Hi,

Error is different now. I confirmed all dependencies are up to date

Error in dispatch_simulations(sim_config, use_future = F, seed = 978,  : 
  attempted 10 percent of total iterations in single thread; something is not right, here's the most recent error: Error in `[.data.frame`(data, , gname): undefined columns selected

**Comment by maxgriswold** [comment]
In the model args for csa, try setting gname = "treatment_date" rather than "treatment_year". Does the error persist?

`csa <- list(
name="CSA",
type="did",
model_call="att_gt",
model_formula= ~ unemploymentrate,
model_args=list(yname="crude.rate", tname="year", idname="state",
gname="treatment_date", xformla = formula("~ unemploymentrate")),
se_adjust=c("none"))`

**Comment by dbent33** [comment]
@maxgriswald that seems to have done the trick thank you

**Comment by maxgriswold** [comment]
No problem. 

If you don't mind @dbent33 , where did you see the argument "treatment"year" in the documentation? If you are able to identify this, I can change it to be correct for future users.

**Comment by dbent33** [comment]
@maxgriswold  I attended a workshop at ICHPS 2025 recently where this syntax was shared. Beth Ann Griffin, among others from RAND, gave this presentation, and the script was embedded, so the documentation fix might be isolated to that audience.
